using Microsoft.EntityFrameworkCore;
using WebCRM.Core.Entities;
using WebCRM.Core.Interfaces;

namespace WebCRM.Data.Tests.Interceptors;

// A small model with one entity per audit shape, so the interceptor is tested on its own
// (EF InMemory; no SQL Server needed).

public class AuditedThing : BaseEntity
{
    public string Name { get; set; } = string.Empty;
}

public class CreatedOnlyThing : ICreationAudited
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public string CreatedBy { get; set; } = string.Empty;
}

public class UpdatedOnlyThing : IModificationAudited
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public DateTime? UpdatedAt { get; set; }
    public string? UpdatedBy { get; set; }
}

public class PlainThing
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class AuditTestDbContext(DbContextOptions<AuditTestDbContext> options) : DbContext(options)
{
    public DbSet<AuditedThing> AuditedThings => Set<AuditedThing>();
    public DbSet<CreatedOnlyThing> CreatedOnlyThings => Set<CreatedOnlyThing>();
    public DbSet<UpdatedOnlyThing> UpdatedOnlyThings => Set<UpdatedOnlyThing>();
    public DbSet<PlainThing> PlainThings => Set<PlainThing>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // rowversion is generated by SQL Server; InMemory has nothing to fill it with.
        modelBuilder.Entity<AuditedThing>().Ignore(e => e.RowVersion);
    }
}

public sealed class FakeCurrentUser : ICurrentUser
{
    public string? UserId { get; set; }

    public int Calls { get; private set; }

    public ValueTask<string?> GetUserIdAsync(CancellationToken cancellationToken = default)
    {
        Calls++;
        return ValueTask.FromResult(UserId);
    }
}

public sealed class FakeTimeProvider(DateTimeOffset utcNow) : TimeProvider
{
    public DateTimeOffset UtcNow { get; set; } = utcNow;

    public override DateTimeOffset GetUtcNow() => UtcNow;
}
